services:
  - type: web
    name: portfoliohub-api
    env: node
    buildCommand: |
      npm install
      cd client && npm install && npm run build
    startCommand: node minimal-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
