services:
  - type: web
    name: portfoliohub-api
    env: node
    buildCommand: npm install
    startCommand: node minimal-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
